version: '3.8'

services:
  motion-index-api:
    build:
      context: ../../
      dockerfile: deployments/docker/Dockerfile.dev
    ports:
      - "6000:6000"
      - "2345:2345"  # Delve debugger port
    volumes:
      - ../../:/app
      - /app/tmp  # Exclude tmp directory from volume mount
    environment:
      - PORT=6000
      - ENVIRONMENT=local
      - PRODUCTION=false
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:5174
      # DigitalOcean Services - use environment variables or .env file
      - DO_SPACES_KEY=${DO_SPACES_KEY}
      - DO_SPACES_SECRET=${DO_SPACES_SECRET}
      - DO_SPACES_BUCKET=${DO_SPACES_BUCKET:-motion-index-docs}
      - DO_SPACES_REGION=${DO_SPACES_REGION:-nyc3}
      # OpenSearch/Elasticsearch
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT:-25060}
      - ES_USERNAME=${ES_USERNAME:-doadmin}
      - ES_PASSWORD=${ES_PASSWORD}
      - ES_USE_SSL=${ES_USE_SSL:-true}
      - ES_INDEX=${ES_INDEX:-documents}
      # Authentication
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - JWT_SECRET=${JWT_SECRET:-dev-jwt-secret-change-in-production}
      # AI Services
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4}
      # Processing Configuration
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-104857600}
      - MAX_WORKERS=${MAX_WORKERS:-10}
      - BATCH_SIZE=${BATCH_SIZE:-50}
      - PROCESS_TIMEOUT=${PROCESS_TIMEOUT:-5m}
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_FORMAT=${LOG_FORMAT:-text}
      - ENABLE_REQUEST_LOGGING=${ENABLE_REQUEST_LOGGING:-true}
      - ENABLE_ERROR_DETAILS=${ENABLE_ERROR_DETAILS:-true}
      - ENABLE_STACK_TRACE=${ENABLE_STACK_TRACE:-true}
    networks:
      - motion-index-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Local Redis for development (if needed for caching)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - motion-index-network
    restart: unless-stopped
    profiles:
      - with-redis

  # Optional: Local OpenSearch for development (if not using DigitalOcean Managed)
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - cluster.name=motion-index-cluster
      - node.name=motion-index-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - motion-index-network
    restart: unless-stopped
    profiles:
      - with-opensearch

networks:
  motion-index-network:
    driver: bridge